update workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,3 +1,46 @@
+# name: Publish Package
+
+# on:
+#   push:
+#     branches:
+#       - main
+
+# jobs:
+#   release:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: 🚀 Checkout repository
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0 # Fetch all history for all branches and tags
+#           persist-credentials: false
+
+#       - name: 📦 Set up Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           registry-url: "https://npm.pkg.github.com"
+#           scope: "@kevbost"
+#           node-version: "20.x"
+
+#       - name: 🔨 Install dependencies
+#         run: npm install
+
+#       - name: 🔄 Bump version
+#         run: node scripts/bump-version.js
+
+#       - name: 🏷️ Commit version bump
+#         run: |
+#           git config --global user.name 'github-actions[bot]'
+#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+#           git add package.json
+#           git commit -m "chore: bump version" || exit 0  # Ensure it doesn't fail if there's nothing to commit
+
+#       - name: 📭 Publish package to GitHub Package Registry
+#         run: npm publish
+#         env:
+#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 name: Publish Package
 
 on:
@@ -42,6 +85,11 @@ jobs:
             echo "::set-output name=version_type::patch"
           fi
 
+      - name: 🏷️ Set Git Config
+        run: |
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+
       - name: 🔄 Bump version
         run: |
           # Use the version_type output from the previous step to bump the correct version
@@ -50,8 +98,6 @@ jobs:
 
       - name: 🏷️ Commit version bump
         run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git add package.json
           git commit -m "chore: bump version" || exit 0 # Ensure it doesn't fail if there's nothing to commit
 
